"""empty message

Revision ID: b88922b87e1f
Revises: 649eb3a8195d
Create Date: 2019-03-04 11:30:08.361980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88922b87e1f'
down_revision = '649eb3a8195d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('a', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'a')
    # ### end Alembic commands ###
