"""empty message

Revision ID: df871e6d2fbe
Revises: b88922b87e1f
Create Date: 2019-03-04 11:32:09.908963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df871e6d2fbe'
down_revision = 'b88922b87e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'a')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('a', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'create_time')
    # ### end Alembic commands ###
